# 方块恢复 BlockRestore 插件
# 作者：Month_Light

# 插件版本号
version: 1.0.1

# 注: 不支持命令重载, 需要重启插件才能重新载入!

# 方块恢复数据配置 (Value 为毫秒, 1000毫秒 = 1秒)
#
# v1.0.1 更新: 去除副 Id 不兼容
#
# STONE: # 当武器子弹破坏石头
#   Value: 2000 # 恢复时间为 2 秒
# 20: # 当武器子弹破坏玻璃
#   Value: 1000 # 恢复时间为 1 秒
List: []

# 方块恢复队列定时器检测周期 (Tick) (20Tick = 1秒) (默认 1 秒)
# 每多长时间检测一次方块恢复队列的数据
# 当数据符合恢复时间则处理
CheckPeriod: 20

# 是否开启 WorldGuard 区域功能 Hook
# 则当武器子弹射中的方块有 WG 区域则阻止破坏 (不包含 '__global__' 区域)
WorldGuardHook: false

# 是否开启当插件卸载后恢复所有的队列方块
DisableRestore: true
